trigger:
- main

pool:
  name: Default      # your Mac agent
  demands:
    - agent.os -equals Darwin

variables:
  solution: 'Mywebapp.sln'   # at repo root
  configuration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore $(solution)
  displayName: 'Restore NuGet packages'

- script: dotnet build $(solution) --configuration $(configuration)
  displayName: 'Build solution'

- script: dotnet test $(solution) --configuration $(configuration)
  displayName: 'Run tests'